version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "rust-test"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
    ports:
      - "5432:5432"
    volumes:
      - .:/docker-entrypoint-initdb.d
  admin:
    image: adminer
    restart: always
    depends_on: 
      - db
    ports:
      - 8080:8080